package hi.cord.com.domain.news;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import org.springframework.data.annotation.Transient;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

//@Document(collection = "news")
@Data
@DynamoDBTable(tableName = "Keywords")
public class NewsData implements Serializable {
    //    @Id
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String pk;

    //    @Indexed(unique = true)
    private long idx;

    @DynamoDBAttribute
    private String headerImage;

    @DynamoDBAttribute
    private String title;

    @DynamoDBAttribute
    private String content;

    @DynamoDBAttribute
    private List<String> tags;

    @DynamoDBAttribute
    private List<String> images;

    @DynamoDBAttribute
    private String fromSource;

    @DynamoDBAttribute
    private Date createdDate;

    @DynamoDBAttribute
    private String createdBy;

    @DynamoDBAttribute
    private Date modifiedDate;

    @DynamoDBAttribute
    private String modifiedBy;

    @DynamoDBAttribute
    private boolean isActived;

    /*
     * Paging Part
    */
    @Transient
    private int pageIndex;

    @Transient
    private int pageSize;

    public NewsData() {

    }

    public NewsData(String pk, long idx) {
        this.pk = pk;
        this.idx = idx;
    }
}