#########################
#### Profile Setting ####
#########################
spring:
  profiles:
    active: dev
---
#############################
#### Profile Information ####
#############################
spring:
  profiles: dev
shun:
  name: Development
  message: This is a ${shun.name} Profile
  servers:
    - www.dev.com
server:
  address: 127.0.0.1
  port: 5000
---
spring:
  profiles: qa
name: qa
shun:
  name: QA
  message: This is a ${shun.name} Profile
  servers:
    - www.qa.com
server:
  address: 127.0.0.1
  port: 5000
---
spring:
  profiles: prod
shun:
  name: Production
  message: This is a ${shun.name} Profile
  servers:
    - www.prod.com
server:
  address: 127.0.0.1
  port: 5000
---
#############################
#### Custom TaskExecutor ####
#############################
shun:
  thread:
    timeout: 2
    core-size: 10
    max-pool: 20
    queue-capacity: 25
---
######################
#### Spring       ####
######################
spring:
  ###########################
  #### MariaDB1 - Common ####
  ###########################
  datasource:
    url: jdbc:mysql://${server.address}:3306/shooney_content
    username: developer
    password: developer@
    driver-class-name: com.mysql.jdbc.Driver
    initialize: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    # If This false Not workign ddl-auto
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  #Redis
#  redis:
#    host: 127.0.0.1
#    password:
#    port: 6379
#    ssl: true
#    timeout: 600000
#    pool:
#      max-active: 10
#      max-idle: 8
#      max-wait: 4
---
#################
#### Logging ####
#################
logging:
  level:
    ROOT: INFO
    org:
      springframework:
        web: INFO
      hibernate: INFO
  pattern:
    level:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /Users/HunSeol/log/shooney/