spring:
  profiles: test
name: test-YAML
environment: test
servers:
  - www.abc.test.com
  - www.xyz.test.com

---
spring:
  profiles: prod
name: prod-YAML
environment: production
servers:
  - www.abc.com
  - www.xyz.com

---
#mongodb
spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: shooney
#      username: shooney
#      password: blue1220@


