package hi.cord.com.log.dynamo.nlp.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import org.springframework.data.annotation.Transient;

import java.io.Serializable;
import java.util.Date;

@Data
@DynamoDBTable(tableName = "NlpPhrase")
public class NlpPhrase implements Serializable {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String where;

    @DynamoDBAttribute
    private Object phrase;

    @DynamoDBTypeConvertedTimestamp(pattern = "yyyy-MM-dd")
    private Date createdDate;

    /*
     * Pagination Part
    */
    @Transient
    private int pageIndex;

    @Transient
    private int pageSize;

    public NlpPhrase() {

    }

    public NlpPhrase(String where) {
        this.where = where;
    }
}