package hi.cord.com.user.dynamo.domain.keywords;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import org.springframework.data.annotation.Transient;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

@Data
@DynamoDBTable(tableName = "Keywords")
public class Keywords implements Serializable {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

//    @DynamoDBIndexHashKey(globalSecondaryIndexName = "idx")
//    private long idx;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute(attributeName = "KeywordType")
    private KeywordType type;

    @DynamoDBAttribute
    private List<String> keywords;

    @DynamoDBAttribute
    private List<String> tags;

    @DynamoDBAttribute
    private String fromSource;

    @DynamoDBTypeConvertedTimestamp(pattern = "yyyy-MM-dd")
    private Date createdDate;

    @DynamoDBAttribute
    private String createdBy;

    @DynamoDBAttribute
    private boolean isActived;

    /*
     * Pagination Part
    */
    @Transient
    private int pageIndex;

    @Transient
    private int pageSize;

    public Keywords() {
        if (this.createdDate == null) {
            createdDate = new Date();
        }
    }

    public Keywords(String id) {
        this.id = id;
    }
}