spring:
  profiles: test
name: test-YAML
environment: test
servers:
  - www.abc.test.com
  - www.xyz.test.com

---
spring:
  profiles: prod
name: prod-YAML
environment: production
servers:
  - www.abc.com
  - www.xyz.com

---

spring:
  data:
    #mongodb
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: shooney
#      username: shooney
#      password: blue1220@
    redis:
      repositories:
        enabled: false
#  #Redis
#  redis:
#    host: 127.0.0.1
#    password:
#    port: 6379
#    ssl: true
#    timeout: 600000
#    pool:
#      max-active: 10
#      max-idle: 8
#      max-wait: 4

  #Java Mail
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: onm10114@gmail.com
    password: blue1220
    port: 587


