spring:
  profiles: qa
name: qa-YAML
environment: qa
messages: This is a qa profile
servers:
  - www.test.com
---
spring:
  profiles: dev
name: dev-YAML
environment: dev
messages: This is a dev profile
servers:
  - www.dev.com
---
spring:
  profiles: prod
name: prod-YAML
environment: production
servers:
  - www.product.com
---
######################
#### Spring       ####
######################
spring:
  data:
    #mongodb
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: shooney
#      username: shooney
#      password: blue1220@
    redis:
      repositories:
        enabled: false
#  #Redis
#  redis:
#    host: 127.0.0.1
#    password:
#    port: 6379
#    ssl: true
#    timeout: 600000
#    pool:
#      max-active: 10
#      max-idle: 8
#      max-wait: 4

  #Java Mail
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: onm10114@gmail.com
    password: blue1220
    port: 587
  # MariaDB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shooney
    username: hooney
    password: blue1220@

######################
#### AWS          ####
######################
amazon:
  dynamodb:
    endpoint: http://localhost:8000/
  aws:
    accesskey: AKIAJEK5RTYCEBDEBOLA
    secretkey: q2n3eYuSJwthTz847hV5uRGM7w

######################
#### Securty      ####
######################
#security:
#  oauth2:
#    client:
#      clientId: 233668646673605
#      clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
#      accessTokenUri: https://graph.facebook.com/oauth/access_token
#      userAuthorizationUri: https://www.facebook.com/dialog/oauth
#      tokenName: oauth_token
#      authenticationScheme: query
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: https://graph.facebook.com/me